//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attandence
    {
        public int AID { get; set; }
        public Nullable<int> Eid { get; set; }
        public Nullable<System.DateTime> IN { get; set; }
        public Nullable<System.DateTime> OUT { get; set; }
        public Nullable<bool> DelStatus { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
