//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employee()
        {
            this.tbl_Attandence = new HashSet<tbl_Attandence>();
        }
    
        public int Eid { get; set; }
        public string EName { get; set; }
        public Nullable<decimal> ESalary { get; set; }
        public Nullable<int> Did { get; set; }
        public string EGender { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Attandence> tbl_Attandence { get; set; }
        public virtual tbl_Department tbl_Department { get; set; }
    }
}
